#![no_std]

//! Core traits that make up the bittwiddler package.
//!
//! Both autogenerated and human-written code will depend on the contents of this crate.

pub mod prelude;

// fixme
pub trait FieldAccessor {}

mod bit_access;
mod property;
mod workarounds;
