[workspace]
resolver = "2"

members = [
    "bittwiddler-core",
    "bittwiddler-dsl",
    "bittwiddler-example-test",
    "bittwiddler-macros", "bittwiddler-textfile",
]

[profile.release]
debug = true
